### ISSUE TITLE
Add JSON syntax highlighting

### ISSUE THREAD

**Issue by Higgs1** [Higgs1/Time-Clickers-Save-Game-Editor-HTML5#2]
Add JSON highlighting to make things pretty.

**Comment by manniL** [comment]
For syntax highlighting, check out [this SO answer](http://stackoverflow.com/questions/4810841/how-can-i-pretty-print-json-using-javascript) (or [this code snippet](http://jsfiddle.net/KJQ9K/554/)) ;)

**Comment by Higgs1** [comment]
Thanks, that code snippet is very nice and so simple too! I was looking into all these complex syntax highlighty and bracket matchy and line number-y heavy libraries that would probably lag the browser on lower end devices a bunch, even though I really like some of them (I should have linked them in the opening post, my bad). 
Now I'm really having trouble choosing between something simple like the snippet you linked to or a big, fancy library, hrmmm... :confounded:
